version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s:%(lineno)d - %(levelname)s - [%(user_id)s] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_general:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/bot_general.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8

  file_gemini:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/gemini_api.log
    maxBytes: 5242880
    backupCount: 3
    encoding: utf-8

  file_database:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/database.log
    maxBytes: 5242880
    backupCount: 3
    encoding: utf-8

  file_user_messages:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/user_messages.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8

# УДАЛЯЕМ ОБРАБОТЧИК file_reminders

loggers:
  gemini_api:
    level: DEBUG
    handlers: [console, file_gemini]
    propagate: no

  database:
    level: DEBUG
    handlers: [console, file_database]
    propagate: no

  user_messages:
    level: INFO
    handlers: [console, file_user_messages]
    propagate: no

  # УДАЛЯЕМ ЛОГГЕР reminders

  __main__:
    level: INFO
    handlers: [console, file_general]
    propagate: no

  default_logger:
      level: INFO
      handlers: [console, file_general]
      propagate: no

root:
  level: WARNING
  handlers: [console, file_general]
  formatter: simple
